export const ADD_BOOKING = 'ADD_BOOKING';
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const GET_SINGLE_BOOKING = 'GET_SINGLE_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const SEARCH_BOOKING = 'SEARCH_BOOKING';
export const SORT_BOOKING = 'SORT_BOOKING';
